### ISSUE TITLE
Server fails to fully remove players on disconnect/exit (Phase 0)

### ISSUE THREAD

**Issue by MaxThePrisberry** [MaxThePrisberry/canvas-conundrum#7]
I've only found this error during phase 0 testing but it could exist in other phases. When I reload the player client (simulate disconnect and reconnect because we haven't made cookie tracking yet) the server correctly identifies that the player has disconnected and logs a message, correctly updates the connected player count, but does not remove the role of the player from the totals and the role is sent to future players as filled. 

Attached is the lobby status with the incorrect totals and the server log.

{"event":"SETUP_TO_CLIENT_LOBBY_STATUS","payload":{"allPlayersReady":false,"currentPlayers":1,"gameStartEligible":false,"hasHost":false,"maxPlayers":64,"minPlayers":4,"playerRoles":{"art_enthusiast":1,"detective":1,"janitor":0,"tourist":0},"readyPlayers":1,"waitingMessage":"Waiting for 3 more player(s) to be ready"},"timestamp":"2025-09-02T10:53:27-07:00"}

2025/09/02 10:48:18 main.go:29: Starting Canvas Conundrum Server on port 8080 in development mode
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for general/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for general/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for general/hard
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for geography/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for geography/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for geography/hard
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for history/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for history/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for history/hard
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for music/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for music/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for music/hard
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for science/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for science/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for science/hard
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for video_games/easy
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for video_games/medium
2025/09/02 10:48:18 trivia_service.go:72: Loaded 50 questions for video_games/hard
2025/09/02 10:48:18 trivia_service.go:76: Total trivia questions loaded: 900
2025/09/02 10:48:18 main.go:136: All services initialized successfully
2025/09/02 10:48:18 main.go:61: Server listening on port 8080
2025/09/02 10:48:36 game_manager.go:172: Player 6702855d-7ef8-497b-aae8-030199a5dbdf joined the game
2025/09/02 10:49:00 player_handler.go:19: Player 6702855d-7ef8-497b-aae8-030199a5dbdf sent event: SETUP_TO_SERVER_PLAYER_CONFIGURATION
2025/09/02 10:49:00 game_manager.go:444: Player 6702855d-7ef8-497b-aae8-030199a5dbdf configured: role=art_enthusiast, specialties=[history]
2025/09/02 10:53:20 game_manager.go:218: RemovePlayer: Removing player 6702855d-7ef8-497b-aae8-030199a5dbdf (name: White)
2025/09/02 10:53:20 game_manager.go:265: RemovePlayer: Cannot send disconnection notification - broadcastSvc=true, host=false
2025/09/02 10:53:20 game_manager.go:284: Player 6702855d-7ef8-497b-aae8-030199a5dbdf disconnected
2025/09/02 10:53:22 game_manager.go:172: Player adc369b1-5a31-4711-82c2-2f6ef3ed2ee5 joined the game
2025/09/02 10:53:27 player_handler.go:19: Player adc369b1-5a31-4711-82c2-2f6ef3ed2ee5 sent event: SETUP_TO_SERVER_PLAYER_CONFIGURATION
2025/09/02 10:53:27 game_manager.go:444: Player adc369b1-5a31-4711-82c2-2f6ef3ed2ee5 configured: role=detective, specialties=[history]

**Comment by nprisbrey** [comment]
@MaxThePrisberry I'd like some more information about why you perceive this as an issue. According to my understanding, this is expected behavior.

If I understand correctly, this issue is based on the assumption that players should be completely removed from everything immediately upon disconnection.

When a player disconnects, they will potentially reconnect at a future time (except during the puzzle assembly phase). This means that we need to keep track of their data and presence on the server side in some form. We assume on the server that the player can rejoin at any time, meaning that their presence should still be tracked in the game and that roles should still be shown as filled even if the player disconnected for a second. This behavior is justified based on the assumption that very few players will suddenly up and leave during the middle of the game and never come back. I would argue that if this was to happen, one should either accept this as a crazy challenge or restart the game with the remaining players (if this presents a big enough issue).

**Comment by nprisbrey** [comment]
After deliberation with Max, it became clear that we want different behavior for player disconnects for the setup phase vs all later phases. During setup if a player disconnects, we want to remove them from all counts, only holding on to their information to aid with reconnection later. If the game has already started, however, hold on to their position in the game and keep their spot held for future reconnection, acknowledging that the player can't reconnect during the puzzle assembly phase.

**Comment by nprisbrey** [comment]
Should now be addressed in the backend.

**Comment by MaxThePrisberry** [comment]
Problem still exists.

2025/09/07 00:54:08 game_manager.go:280: RemovePlayer: Setup phase - player removed from counts. Connected: 0, Ready: 0
2025/09/07 00:54:08 game_manager.go:295: RemovePlayer: Sending disconnection notification to host for player 061bf821-ddd4-4d75-8799-a5fc775c8d0d
2025/09/07 00:54:08 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_TO_HOST_PLAYER_DISCONNECTED to host
2025/09/07 00:54:08 game_manager.go:334: RemovePlayer: Disconnection notification sent
2025/09/07 00:54:08 game_manager.go:356: Player 061bf821-ddd4-4d75-8799-a5fc775c8d0d disconnected
2025/09/07 00:54:08 game_manager.go:365: Sending roster update to host after player 061bf821-ddd4-4d75-8799-a5fc775c8d0d disconnected
2025/09/07 00:54:08 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:54:10 game_manager.go:200: Player 813e6cf3-50ac-4d6a-88b2-3169b05d7198 joined the game
2025/09/07 00:54:10 game_manager.go:215: Sending roster update to host after player 813e6cf3-50ac-4d6a-88b2-3169b05d7198 joined
2025/09/07 00:54:10 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:54:18 host_handler.go:19: Host sent event: SYSTEM_PING
2025/09/07 00:54:18 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_PONG to host
2025/09/07 00:54:21 game_manager.go:246: RemovePlayer: Removing player 813e6cf3-50ac-4d6a-88b2-3169b05d7198 (name: )
2025/09/07 00:54:21 game_manager.go:280: RemovePlayer: Setup phase - player removed from counts. Connected: 0, Ready: 0
2025/09/07 00:54:21 game_manager.go:295: RemovePlayer: Sending disconnection notification to host for player 813e6cf3-50ac-4d6a-88b2-3169b05d7198
2025/09/07 00:54:21 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_TO_HOST_PLAYER_DISCONNECTED to host
2025/09/07 00:54:21 game_manager.go:334: RemovePlayer: Disconnection notification sent
2025/09/07 00:54:21 game_manager.go:356: Player 813e6cf3-50ac-4d6a-88b2-3169b05d7198 disconnected
2025/09/07 00:54:21 game_manager.go:365: Sending roster update to host after player 813e6cf3-50ac-4d6a-88b2-3169b05d7198 disconnected
2025/09/07 00:54:21 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:54:23 game_manager.go:200: Player 0e0b9a18-f977-4394-b089-4393ca1ad21f joined the game
2025/09/07 00:54:23 game_manager.go:215: Sending roster update to host after player 0e0b9a18-f977-4394-b089-4393ca1ad21f joined
2025/09/07 00:54:23 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:54:48 host_handler.go:19: Host sent event: SYSTEM_PING
2025/09/07 00:54:48 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_PONG to host
2025/09/07 00:54:53 player_handler.go:18: Player 0e0b9a18-f977-4394-b089-4393ca1ad21f sent event: SYSTEM_PING
2025/09/07 00:55:16 game_manager.go:246: RemovePlayer: Removing player 0e0b9a18-f977-4394-b089-4393ca1ad21f (name: )
2025/09/07 00:55:16 game_manager.go:280: RemovePlayer: Setup phase - player removed from counts. Connected: 0, Ready: 0
2025/09/07 00:55:16 game_manager.go:295: RemovePlayer: Sending disconnection notification to host for player 0e0b9a18-f977-4394-b089-4393ca1ad21f
2025/09/07 00:55:16 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_TO_HOST_PLAYER_DISCONNECTED to host
2025/09/07 00:55:16 game_manager.go:334: RemovePlayer: Disconnection notification sent
2025/09/07 00:55:16 game_manager.go:356: Player 0e0b9a18-f977-4394-b089-4393ca1ad21f disconnected
2025/09/07 00:55:16 game_manager.go:365: Sending roster update to host after player 0e0b9a18-f977-4394-b089-4393ca1ad21f disconnected
2025/09/07 00:55:16 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:55:18 game_manager.go:200: Player 14f69bfb-6737-4f6c-b649-b02052e2da85 joined the game
2025/09/07 00:55:18 game_manager.go:215: Sending roster update to host after player 14f69bfb-6737-4f6c-b649-b02052e2da85 joined
2025/09/07 00:55:18 broadcast_service.go:61: SendToHost: Successfully sent event SETUP_TO_HOST_PLAYER_ROSTER to host
2025/09/07 00:55:18 host_handler.go:19: Host sent event: SYSTEM_PING
2025/09/07 00:55:18 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_PONG to host
2025/09/07 00:55:47 host_handler.go:19: Host sent event: SYSTEM_PING
2025/09/07 00:55:47 broadcast_service.go:61: SendToHost: Successfully sent event SYSTEM_PONG to host
2025/09/07 00:55:48 player_handler.go:18: Player 14f69bfb-6737-4f6c-b649-b02052e2da85 sent event: SYSTEM_PING

**Comment by nprisbrey** [comment]
Feeling a lot more confident about 1d22944. There was an issue where functions weren't updated to count only active players.
